#!/bin/bash

echo "======================================"
echo "Deploy Agente Executor - CORREÇÕES FINAIS"
echo "======================================"
echo ""
echo "Este script faz o deploy da edge function agente-execucao com as correções:"
echo "1. ✅ Suporte para mudança de progresso (ex: 'mude para 50%')"
echo "2. ✅ Detecção melhorada de ações mencionadas (múltiplas palavras-chave)"
echo "3. ✅ System prompt atualizado (não pede confirmações desnecessárias)"
echo "4. ✅ Normalização de texto (remove acentos)"
echo "5. ✅ Keywords expandidas para melhor detecção"
echo "6. ✅ Suporte para bloquear/desbloquear ações"
echo "7. ✅ Suporte para adicionar observações"
echo "8. ✅ Extração correta do user_id do token JWT"
echo ""
echo "Executando deploy..."
echo ""

npx supabase functions deploy agente-execucao

echo ""
echo "======================================"
echo "Deploy concluído!"
echo "======================================"
echo ""
echo "TESTE AGORA:"
echo ""
echo "1. Drag and Drop:"
echo "   - Arraste cards entre colunas no Kanban"
echo "   - Verifique que ficam fixos (sem precisar refresh)"
echo ""
echo "2. Agente Executor - Mudança de Progresso:"
echo "   Digite: 'mude o progresso para 50% da ação implementar sistema de gestão financeira'"
echo "   Esperado: 📊 Progresso atualizado para 50%"
echo ""
echo "3. Agente Executor - Iniciar Ação:"
echo "   Digite: 'coloque a primeira ação em andamento'"
echo "   Esperado: ▶️ Ação iniciada (em andamento)"
echo ""
echo "4. Agente Executor - Confirmar:"
echo "   Digite: 'posso atualizar a segunda ação?'"
echo "   Agente sugere algo"
echo "   Digite: 'confirmo' ou 'isso, confirmado'"
echo "   Esperado: Agente executa sem pedir confirmação novamente"
echo ""
echo "Leia CORRECOES_FINAIS_KANBAN_AGENTE.md para mais detalhes!"
echo ""
