#!/bin/bash

# Script de Deploy da Edge Function consultor-rag
# As correções estão implementadas mas precisam ser deployadas!

echo "=========================================="
echo "DEPLOY: consultor-rag (Correções Definitivas)"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANTE: Você precisa fazer login no Supabase primeiro!"
echo ""
echo "Execute os seguintes comandos:"
echo ""
echo "1. Login no Supabase:"
echo "   npx supabase login"
echo ""
echo "2. Link do projeto:"
echo "   npx supabase link --project-ref gljoasdvlaitplbmbtzg"
echo ""
echo "3. Deploy da função:"
echo "   npx supabase functions deploy consultor-rag --no-verify-jwt"
echo ""
echo "=========================================="
echo "MUDANÇAS QUE SERÃO DEPLOYADAS:"
echo "=========================================="
echo ""
echo "✅ Parser multi-estratégia (4 camadas)"
echo "✅ JSON mode forçado na OpenAI"
echo "✅ Detectores automáticos de completude"
echo "✅ Timeline atualizada em toda interação"
echo "✅ Validação de fluxo de fases"
echo "✅ Geração automática de Matriz GUT + Escopo"
echo ""
echo "=========================================="
echo "ARQUIVOS MODIFICADOS:"
echo "=========================================="
echo ""
echo "- supabase/functions/consultor-rag/index.ts"
echo "- supabase/functions/consultor-rag/consultor-prompts.ts"
echo ""
echo "Esses arquivos estão PRONTOS para deploy!"
echo ""
