/*
  # Add Narrative Text Column to Data Analyses

  ## Changes
  - Add `narrative_text` column to store formatted Manus-style narrative
  - Add index for faster retrieval of analyses with narratives

  ## Purpose
  Stores the enhanced Manus-style narrative generated by the narrative engine.
  This allows post-analysis queries to access the rich narrative without regeneration.
*/

-- Add narrative_text column
ALTER TABLE data_analyses
ADD COLUMN IF NOT EXISTS narrative_text text;

-- Add comment
COMMENT ON COLUMN data_analyses.narrative_text IS 'Enhanced Manus-style narrative text formatted for display';

-- Create index for analyses with narratives
CREATE INDEX IF NOT EXISTS idx_data_analyses_with_narrative
ON data_analyses(user_id, created_at DESC)
WHERE narrative_text IS NOT NULL;

-- Add index for analysis ID lookups (used by query-analysis function)
CREATE INDEX IF NOT EXISTS idx_data_analyses_id_user
ON data_analyses(id, user_id);
